### ISSUE TITLE
Use .gif format avatar and no animation on the homepage. The article page is normal.bug

### ISSUE THREAD

**Issue by Chow-Ray** [hugo-toha/toha#209]
- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description

Use .gif format avatar and no animation on the homepage. The article page is normal.Use .jpg or .png，is normal。In the previous version, there is no such problem。

**Comment by Chow-Ray** [comment]
@hossainemruz plz
**fix ：**`layouts\partials\sections\home.html`Line 108.

If `<img src="{{ $authorImage.RelPermalink }}"` is replaced by `<img src="{{ $authorImage | relURL }}"` , there will be no problem. Why does this happen?

**Comment by hossainemruz** [comment]
@Chow-Ray can you please explain the issue more? I actually didn't understand it properly.

**Comment by Kaligule** [comment]
To me it sounds like @Chow-Ray want to say the following:

If you use a (possibly animated?) `gif` (instead of `jpg` or `png` as an author image (as specified in the `author.yaml` as `image:`), then the animations (like the gauges for the skills) will not start playing.

I am not able to replicate this bug.
