### ISSUE TITLE
New feature in education: supervisors & thesis

### ISSUE THREAD

**Issue by IhnwhiHeo** [hugo-toha/toha#400]
Hi folks,

I appreciate this awesome theme for a personal website. I would like to request a new feature for the education section. How about adding a subsection to list supervisors' names and thesis topics? I do see there are rooms for publication, but it would be nice to have separate rooms for the thesis. Likewise, adding supervisor names would make this theme more attractive for those in academia.

Thank you.

**Comment by Rihoj** [comment]
@IhnwhiHeo Can you give an example of how you envision this looking? I would assume that since you can add a URL to the publication you would just link to the copy and allow the additional information to be presented there. However, if you are able to give an example of what you are expecting I can see what I can do.

**Comment by NSerbin** [comment]
And Why not another tab like Languages ?

**Comment by IhnwhiHeo** [comment]
@Rihoj Hello! Currently, there are subsections like CGPA, Publications, and Taken Courses. I would like to add a custom-made subsection such as Advisor(s), Honors and Awards, etc. Tried to add it but it failed (seems like I can only add those that are hard-wired).
