### ISSUE TITLE
Navigation not working when section title is hidden

### ISSUE THREAD

**Issue by stueja** [hugo-toha/toha#494]
## Expected Behavior
Even when the section title is hidden, a click onto the navbar should scroll to the corresponding section.

## Current Behavior
If the section title is hidden (`hideTitle: true` in e. g. `data/en/sections/experiences.yaml`), a click onto "Experiences" in the navbar does nothing.

## Possible Solution
Make the anchor independent from the title.

## Steps to Reproduce

1. set `hideTitle: true` in `data/en/sections/experiences.yaml`
2. run `hugo server -D`
3. open the webpage
4. click on "Experiences" in the navbar

### Browsers Affected

- [ ] Chrome
- [ x ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11
- [ x ] Safari 15

**Comment by hossainemruz** [comment]
Thank you @stueja for reporting this issue. In order to fix this, we should still add the respective title header but set it's `display` property to `None` when `hideTitle` is `true`.
Ref: https://github.com/hugo-toha/toha/blob/21344642679180b091ff1772dc0e3d52b0b6584c/layouts/partials/sections/education.html?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L8

This should be done in almost every section templates.

**Comment by stueja** [comment]
Proposed solution, one example amongst others.
```
    {{ if not (.section.hideTitle) }}
    <h1 class="text-center">
        <span id="{{ $sectionID }}"></span>{{ .section.name }}</h1>
    {{ else }}
    <h1 class="text-center" style="display: none">
        <span id="{{ $sectionID }}"></span>{{ .section.name }}</h1>
    {{ end }}
```

**Comment by hossainemruz** [comment]
Sure @stueja. Go ahead.
