### ISSUE TITLE
Home Page Scrolling is Super Laggy in Safari

### ISSUE THREAD

**Issue by shineyruan** [hugo-toha/toha#511]
## Expected Behavior

Scrolling in home page should be smooth

## Current Behavior

Scrolling in home page gets choppy on latest Safari (v15.2)

## Steps to Reproduce

1. Open the latest version of Safari (v15.2)
2. Navigate to the demo website
3. Scroll up and down 
4.

### Browsers Affected

- [x] **Safari 15.2**
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

## Detailed Description

I'm not familiar with web design and don't know how to fix it. But I'm a user of Toha and I got this laggy behavior only on the home page even on M1Max MacBook with the latest version of Safari. Chrome works just fine.

**Comment by hossainemruz** [comment]
I don't have a M1 mac. So, I can't debug the issue. If anyone can contribute the fix, it will be greatly appreciated.

**Comment by stueja** [comment]
I have an M1 MacBook Air with Safari 15.2, and here the scrolling as well as clicking onto the menus results in smooth scrolling. #cantreproduce

**Comment by shineyruan** [comment]
> I have an M1 MacBook Air with Safari 15.2, and here the scrolling as well as clicking onto the menus results in smooth scrolling. #cantreproduce

Could you please help double check if the scrolling still works for you when Safari is in fullscreen mode?

**Comment by stueja** [comment]
@shineyruan , ah, good idea, thanks. I tested it now in fullscreen mode, and still it is not laggy on the example website.

**Comment by shineyruan** [comment]
> @shineyruan , ah, good idea, thanks. I tested it now in fullscreen mode, and still it is not laggy on the example website.

Hi @stueja , I'm wondering if you have noticed a significant frame rate drop when scrolling down from the very top of the home page to the "About" section? If not, could you please help trying https://zhihaoruan.xyz a little bit? 

I'm still getting laggy behavior on my Mac. I'm using the latest macOS Monterey as well.

**Comment by stueja** [comment]
Hi @shineyruan , no, sorry, I haven't noticed a frame rate drop, not on the test site and not on your site. Please find a movie of my experience attached. It's 480p because github does not allow video files larger than 10MB.

https://user-images.githubusercontent.com/9169222/151465906-c529706f-81ed-4fa7-9ab7-0016ccab057a.mov

**Comment by Rihoj** [comment]
I can replicate some lag, as I have the same issue on my site. I am running chrome on a linux system I am guessing the issue is the image size of the background images, and the ability of the browser/computer to render it scrolling correctly. This is just a guess, but when I remove the background-image css attribute, then your site has no issue scrolling.

Recommendation: reduce your image to a much smaller size. I am currently reading it at 6000 x 3375 pixels. If that doesn't work, then please let me know, and since I can replicate some lag, I will see if I can dig into other options.

As a note: I don't have any issues on the guide https://hugo-toha.github.io/ the image size is 1920 x 1078 px.

**Comment by shineyruan** [comment]
> I can replicate some lag, as I have the same issue on my site. I am running chrome on a linux system I am guessing the issue is the image size of the background images, and the ability of the browser/computer to render it scrolling correctly. This is just a guess, but when I remove the background-image css attribute, then your site has no issue scrolling.
> 
> Recommendation: reduce your image to a much smaller size. I am currently reading it at 6000 x 3375 pixels. If that doesn't work, then please let me know, and since I can replicate some lag, I will see if I can dig into other options.
> 
> As a note: I don't have any issues on the guide https://hugo-toha.github.io/ the image size is 1920 x 1078 px.

Ah, nice catch. Indeed this issue was due to the large size of my avatar and my background image. I reduced the size of them and it works! Thank you!
