### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by hossainemruz** [hugo-toha/toha#59]
https://dev.to/akhilarjun/one-line-dark-mode-using-css-24li

**Comment by alex-bezek** [comment]
@hossainemruz FWIW this is what it does to my site
Before
![image](https://user-images.githubusercontent.com/8029578/96395551-e7fdcf00-1192-11eb-964b-ea8f524cd079.png)
![image](https://user-images.githubusercontent.com/8029578/96395007-75d8ba80-1191-11eb-9d2a-42c363e81030.png)

After
![image](https://user-images.githubusercontent.com/8029578/96395724-622e5380-1193-11eb-8967-6911d61757b2.png)
![image](https://user-images.githubusercontent.com/8029578/96394997-6eb1ac80-1191-11eb-9876-7eedf5bf5a78.png)

I think largely it does the job well but there are a few sets of text that need some attention in order for their contrast ratio to be high enough. i assume if we figure those out we could easily turn this on with a feature flag in the config.yml to make this passive?

**Comment by yeganathan** [comment]
Hey @hossainemruz can you please tell me for darkmode in which CSS file should be the following code added,

```
html[theme='dark-mode'] {
    filter: invert(1) hue-rotate(180deg);
}
```

**Comment by hossainemruz** [comment]
I am not sure yet @yeganathan. Probably, @alex-bezek can help.

**Comment by yeganathan** [comment]
Thanks for the reply! @hossainemruz 
Let me check with @alex-bezek

**Comment by alex-bezek** [comment]
@yeganathan18 if you add a css file to this location, it will get picked up and included in the build
https://github.com/alex-bezek/blog/blob/master/static/assets/css/style.css

**Comment by yeganathan18** [comment]
@alex-bezek Thanks for the help :)

**Comment by donfiguerres** [comment]
I'm experimenting with using DarkReader to enable dark mode in toha. My branch is [here](https://github.com/donfiguerres/toha/tree/dev-dark-theme).
So far, the result is pretty decent. Not sure if that's biased because I'm using the DarkReader browser plugin. I think a native CSS for dark mode is faster but still, this gets the job done with minimal effort.

![image](https://user-images.githubusercontent.com/12525903/119544484-53acb800-bdc4-11eb-9fd9-4b319ddc4be8.png)
![image](https://user-images.githubusercontent.com/12525903/119544712-8eaeeb80-bdc4-11eb-939a-2b45be2f3c70.png)

Website URL: https://donfiguerres.github.io/

**Comment by donfiguerres** [comment]
Hi everyone! I've made a pull request to support dark theme via darkreader. Hoping that it gets approved.
I'm planning to add it to the toha documentation if the pull request gets approved.
