### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by serverfriendsorg** [hugo-toha/toha#96]
First of all thank you for this great theme! I'm using it for my site currently and want to know
if there is a way to translate the "at" in the About me area? 
For example "Job title **at** CompanyXYZ" and under Work experience the text "Responsibilities" and "Present" for the current position. 

Thanks in advance.

**Comment by hossainemruz** [comment]
>is a way to translate the "at" in the About me area?

No. Currently, it is hard coded [here](https://github.com/hossainemruz/toha/blob/1df947bed2dfc2a529eead5138820c2aefbc7509/layouts/partials/sections/about.html#L15). I don't think only providing a translation for `at` is sufficient. Sentence structure differs in different languages. In some languages, the Company part will go first. Perhaps, we can take the whole sentence as input from the user instead of generating automatically.

>under Work experience the text "Responsibilities" and "Present" for the current position.

We can add translation for these.

**Comment by lgatellier** [comment]
Hi @hossainemruz,
I think this issue can be closed, since these words have been added to i18n configuration in #234. 😉
